### PR TITLE
Scss refactor for auth module

### PR DESCRIPTION
**Pull request by version0chiro**
## What I have done:
- Made a '.scss' file for auth
- converted the styled-components into className
- will be converting into modular soon

Just wanted to confirm if this manner is what I should follow before going very deep into it, like an initial review

### CODE REVIEW

**Comment by bmarvinb** [comment]
@version0chiro looks good

**Comment by bmarvinb** [comment]
@version0chiro you you still working on it?

**Comment by version0chiro** [comment]
Yes Yes, I will convert the remaining modules into scss file

**Comment by version0chiro** [comment]
Also can you add hacktober fest into the tags if possible?

**Comment by bmarvinb** [comment]
@version0chiro yes

**Comment by version0chiro** [comment]
I guess I have finished all the files and replaced SCSS, you can check

Also please add the project into hacktoberfest listing  with tags and accepted PR🙏

**Comment by bmarvinb** [comment]
@version0chiro fix conflict with package-lock please, I add this tag

**Comment by version0chiro** [comment]
Did the changes with lock to counter the merge conflict

**Comment by bmarvinb** [comment]
@version0chiro sorry, conflict again, please fix this, and I will merge it as soon as possible

**Comment by bmarvinb** [comment]
I think it's a lot of change, and I would remove this issue at all

**Comment by version0chiro** [comment]
Should I send a new PR?

**Pull request closed without merging**
