### PR TITLE
Initial design

### PR DESCRIPTION
**Pull request by RanjithSivam**
This is the initial design. Any comments? or changes?

### CODE REVIEW

**Comment by RanjithSivam** [comment]
This is the initial design. Any comments? or changes?

**Comment by bmarvinb** [comment]
@RanjithSivam Hi, it would be great if you attach some screenshots, or a small video

**Comment by RanjithSivam** [comment]
image
I have a few queries.
1. where should I place the images in the project?
2. Can I install antd/icons?
3. can i add more sections to the page? like contacts,etc..

**Comment by bmarvinb** [comment]
1) public/assets
2) yes
3) don't think we need it

**Comment by bmarvinb** [comment]
About design
image

Try to copy this design, use gradient, but you can use your image, and remove join us button, add footer, where you can put github link

**Comment by bmarvinb** [comment]
Also check that
1) when you are guest you can't see any auth routes, like board, if you try to open these routes you should redirect to sign-in page

**Comment by RanjithSivam** [comment]
image

will this work?

**Comment by RanjithSivam** [comment]
@bmarvinb I have completed the design. I have used inline styles but in the future i will move styles into separate scss file.

**Comment by bmarvinb** [comment]
@RanjithSivam merged, congratulations )

**Pull request merged**
