### PR TITLE
Andt upgrade

### LINKED ISSUE #110: Update antd to the latest version

### PR DESCRIPTION
**Pull request by sano2019**
Had to change quite a lot of code to get this working. Please let me know if there are any issues / recommendations for this. Also in terms of code style. This should close #110

### CODE REVIEW

**Comment by bmarvinb** [comment]
@sano2019 look very good, but you have a conflict in Card.js

**Comment by sano2019** [comment]
oops, missed that. I will have a look in a while, hopefully tonight still.

**Comment by sano2019** [comment]
This should fix it. I didn't fetch from upstream, I hadn't forked on a repo before like this ^^

**Comment by bmarvinb** [comment]
Tgis should be another issue

**Comment by bmarvinb** [comment]
Merged

**Pull request merged**
