### PR TITLE
Added-GoogleAuth-saved user using redux

### PR DESCRIPTION
**Pull request by phoenixx1**
Made some import changes for useState and added GoogleAuth functionality, saved the state using React-ContextAPI.
Added button to logout in Boards.js

### CODE REVIEW

**Comment by bmarvinb** [comment]
@phoenixx1 Thanks for your PR! But before it will merged, I have some comments

1. Resolve conflicts
2. Remove code than commented
3. I don't think we need a separate directory for the state here like, just put this to "container" component. This approach is not bad, but what I want consistent approach, and indifferent modules, we didn't use this. Also what I don't like, you named it 'redux', but it's incorrect, first of all, we didn't use redux as a library, second even if we will use it, it is bad naming, we need a more abstract name for it, like 'state' or 'data', because what if we will move to the different state library, like apollo with graphql or xState? 
4. Sort imports alphabetically like in other files, 3rd party and custom imports should have empty row between them
5. Remove console.log from your changes
6. Do not write styles in your <div>, first of all in other components, we use CSS in js. Just open any other file.

**Comment by phoenixx1** [comment]
@bmarvinb    Ok, I'll make the changes.

**Comment by phoenixx1** [comment]
@bmarvinb   
Where I'm supposed to add styling for that div, I don't see any CSS file, actually, I saw you did the same for the email input field.
I have moved both the state files to API folder.

**Comment by bmarvinb** [comment]
@phoenixx1 You still have merge conflicts, can you look at it please?

**Comment by phoenixx1** [comment]
@bmarvinb   
Hey, can you help me with this conflict, as you have refactored major code into new folders, and I'm unable to fetch new files from the origin?

**Comment by bmarvinb** [comment]
@phoenixx1 I used CSS in js, just search 'styled' in imports, and you will found how it used, you create a variable and put CSS there, and after that, you can use this variable in jsx.

**Comment by bmarvinb** [comment]
@phoenixx1 I removed signinform component and put it directly to sign-in page

**Comment by bmarvinb** [comment]
@phoenixx1 Also I renamed AuthorizedNavigation to AuthNavigation and put it to core/layout folder

**Comment by phoenixx1** [comment]
@bmarvinb   
In SignIn.js you have passed history to WrappedSignIn component, then how I'm supposed to use it in SignIn, I tried importing it as a prop but it gave some other infinite loop error.

**Comment by bmarvinb** [comment]
@phoenixx1 Sorry for the dumb advice, but try to find this error in google, I think this should be common error, and you can fix it

**Comment by bmarvinb** [comment]
I will check it tomorrow

**Comment by bmarvinb** [comment]
Congratulations! Works good, merged 👍

**Pull request merged**
