### PR TITLE
Refactor FormCreation

### PR DESCRIPTION
**Pull request by gauraws**
Refactor from class component to functional component using react hooks

### CODE REVIEW

**Comment by bmarvinb** [comment]
Instead of using promises with then use async await please

**Comment by gauraws** [comment]
Are you taking about callback in handleCreate method?

**Comment by bmarvinb** [comment]
Yes

**Comment by gauraws** [comment]
Will fix that

**Comment by gauraws** [comment]
Please review, used async await for callback

**Comment by bmarvinb** [comment]
@gauraws please read my comments, some of them still not fixed, thanks

**Comment by gauraws** [comment]
Can you please be specific what is not fixed? I am missing something here 🙂

**Comment by bmarvinb** [comment]
image

image

Hi, these )

**Comment by gauraws** [comment]
Can you please check this PR again?

**Comment by bmarvinb** [comment]
@gauraws merged, congratulations )

**Pull request merged**
