### PR TITLE
[#67] Add Docker support

### LINKED ISSUE #67: Create docker container for project
We should add docker support to current project, so someone should create config, and test it! This will help other developers setup environment more quickly and easy, and you can learn a lot while implement it!

### PR DESCRIPTION
**Pull request by cyntler**
Closes #67.
@bmarvinb, please CR! :)

### CODE REVIEW

**Comment by bmarvinb** [comment]
@cyntler thanks for pr! 

But I get an error 
image
Is it important what node.js version on my local machine?

**Comment by bmarvinb** [comment]
After I downgraded node to 8.9.0 and run docker-compose up again in builded, but then I get another error 
image

**Comment by cyntler** [comment]
@bmarvinb try to remove node_modules and again run `docker-compose up --build`

**Comment by bmarvinb** [comment]
I will try to test it in next weak, I go to vocation, right know I still get errors (

**Comment by cyntler** [comment]
Ok. The problem was because we had a old version of firebase library. After update all is working now. Please check! :)
I updated the branch.

**Comment by bmarvinb** [comment]
Merged 👍

**Pull request merged**
