### PR TITLE
Redirect to homepage bug resolved

### PR DESCRIPTION
**Pull request by RanjithSivam**
I solved the issue, but the code looks nasty. Let me know if there is any more bugs.

### CODE REVIEW

**Comment by bmarvinb** [comment]
@RanjithSivam you have conflicts, merge new master to your branch, and read my comment please about class components

**Comment by RanjithSivam** [comment]
> @RanjithSivam you have conflicts, merge new master to your branch, and read my comment please about class components

where do i check for comments?

**Comment by bmarvinb** [comment]
image
image

**Comment by RanjithSivam** [comment]
@bmarvinb done.

**Comment by bmarvinb** [comment]
@RanjithSivam for the next time please you prettier for code formatting

**Pull request merged**
