### PR TITLE
Fix #136: Add BoardLink.js prop types

### LINKED ISSUE #136: BoardLink.js prop types
https://github.com/bmarvinb/react-trello-clone/blob/master/src/features/boards/components/BoardLink.js

### PR DESCRIPTION
**Pull request by jayeshchoudhary**
added prop types to BoardLink file as described in issue #136

### CODE REVIEW

**Comment by jayeshchoudhary** [comment]
@Bhavin789 can you please review this

**Comment by bmarvinb** [comment]
@jayeshchoudhary merged

**Comment by jayeshchoudhary** [comment]
@bmarvinb can you please add hactoberfest-accepted label as this pr is under that event

**Comment by bmarvinb** [comment]
@jayeshchoudhary ok

**Pull request merged**
