### PR TITLE
refactor(PasswordForget): refactoring from class to hooks

### PR DESCRIPTION
**Pull request by Armakuji**

### CODE REVIEW

**Comment by bmarvinb** [comment]
@Armakuji check my comment in code please

**Comment by Armakuji** [comment]
@bmarvinb  Where you comment. I haven't found

**Comment by bmarvinb** [comment]
image

**Comment by bmarvinb** [comment]
image

**Comment by Armakuji** [comment]
Your comments don't show up in my files changed.

Screen Shot 2021-10-03 at 3 59 42 AM

**Comment by Armakuji** [comment]
OK, I will fix it.

**Comment by Armakuji** [comment]
I guess you forgot to Submit review.

image

**Comment by Armakuji** [comment]
@bmarvinb I fixed all the comments ✨. Please review again.

**Pull request merged**
