### PR TITLE
[#77] Fix ESLint error

### LINKED ISSUE #77: Docker error with eslint
image

Need to find a solution for this

### PR DESCRIPTION
**Pull request by cyntler**
Closes #77 and #81.

### CODE REVIEW

**Comment by bmarvinb** [comment]
@cyntler still the same, I also will invest some time to this problem later, if nobody won't fix it

**Comment by cyntler** [comment]
@bmarvinb check now please.

**Comment by bmarvinb** [comment]
@cyntler on your local machine this work well?

**Comment by cyntler** [comment]
@bmarvinb Yes, all the time is working fine as I see.

**Comment by bmarvinb** [comment]
@cyntler nice! it works

**Pull request merged**
